### ISSUE TITLE
blank page instead of post

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#1]
Hi Stefan.

I've tested this on both Safari and Firefox, on a Mac.

Individual posts such as http://localhost:8000/resource/dariah-guide-to-data-management-best-practices-in-the-humanities display a blank page. On relaod, the same page will display a `type error: can't convert symbol to string`. 

![Снимок экрана 2019-08-06 в 12 10 17](https://user-images.githubusercontent.com/5304839/62531692-33a0b300-b843-11e9-9f6e-8a60c0668c57.png)

There's a bunch of errors in the Firefox dev console, the first of which is:

`The connection to http://localhost:8000/__webpack_hmr was interrupted while the page was loading. client.js:88`

Could you please take a look?

**Comment by stefanprobst** [comment]
this is already fixed locally -- the issue was that `react-helmet` which we use to inject SEO info in the `<head>` does not understand `React.Fragment`s.
