### ISSUE TITLE
Resource types

### ISSUE THREAD

**Issue by DeborahThorpe** [stefanprobst/dariah-campus-mdx#13]
Hi Stefan,

@ttasovac and I are adding new resource types (we've begun with 'training modules') - but can you tell us how icons work? How do we know the names of icons - is there a list of them?
Thanks,
Debs

**Comment by ttasovac** [comment]
Also, @stefanprobst, just so that you know —  I will be occasionally merging our new content into the master branch. I think it would be an overkill to do pull requests for this at this point, unless there is a conflict, but as long as Debs and I are working on the content, those should be easy to avoid. 

But, yes, we both wondered about the icons...

**Comment by stefanprobst** [comment]
icon keywords need to be mapped to actual icons here: https://github.com/stefanprobst/dariah-campus-mdx/blob/9abe75ccc972477ad90153e4c6729a7724f89e05/src/components/PostPreview/PostPreview.js#L23-L29

if you tell me what you need - or just push an updated `resources.yaml` i can do that

**Comment by ttasovac** [comment]
Are these font awesome icons? If so, which version? Can we use any free icon from here https://fontawesome.com/icons?d=listing&m=free?

**Comment by stefanprobst** [comment]
yes -- we take those from `react-icons`, which includes font-awesome. take a look at [https://react-icons.netlify.com/#/icons/fa](https://react-icons.netlify.com/#/icons/fa) -- i *think* it includes v5, but i'd need to check

**Comment by ttasovac** [comment]
Good to know. I will close this issue now because we have the link to inspect all the available icons so that we can choose what we need...

**Comment by ttasovac** [comment]
@DeborahThorpe, I've looked at the EOSC-supplied resource types again and they're not very useful:

> [type of resource: blog; Jupyter notebook; manual; PDF; source code; training module; videos; website; Wiki; Google presentation; Google spreadsheet; Google Text Document; DOC Word document; XLS spreadsheet document; PPT Powerpoint presentation; others ]

For instance, why are videos in the plural and everything else is singular? why is there video but not audio? what qualifies actually as a training module? etc.

D-C resources are self-contained training objects or videos or audio recordings. I don't think we will be posting slides as a D-C resource. Slides are never enough -- unless they include the recording of a whole lecture, in which case we would classify that as video.

So we really should use only: training module (even though module is itself questionable), video and audio. Audio in case we have a podcast- like thing, which, again, is very unlikely. 

Let me know if I'm missing anything. If not, could you please:

- add video as resource type to all of the individual videos we have (i've set up an icon for that)
- change the resources currently typed as webinar recordings to "video"

**Comment by DeborahThorpe** [comment]
@ttasovac it's just occurred to me that 'Webinar recordings' actually comprise (in the case of the Parthenos webinars anyway): YouTube videos, slides, and textual summaries. So, perhaps 'video' doesn't cover it? What do you think? Would you rather go for 'video' for simplicity's sake, or could we make an extra category for 'webinar capture'?

**Comment by ttasovac** [comment]
yes, you are right. but i still wouldn't create a separate category for it. i would then treat it as a regular online resource. dariahTeach online resources can and often do contain videos, slides etc. but they still come as a package. we'll use video only for video-only things, i.e. keynote lectures or those "little" dariahTeach videos...

--
Belgrade Center for Digital Humanities
http://humanistika.org

**Comment by DeborahThorpe** [comment]
Ok. I'll give webinars the type: 'training module' then (although I agree that, too, is problematic... #dariahTeach courses are known as 'courses', for instance, because they are entire courses!) But for now, let's call them that...
