### ISSUE TITLE
author / editor / contributor

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#15]
Ok, I#m really sorry to be doing this to to you, @stefanprobst, but @DeborahThorpe alerted me that in some of the resources we'll be pointing to, we need to distinguish between authors, editors and contributors. Again, since we want D-C to have rich metadata, we have to be able to cover all those cases.

I suggest to do the following:

- rename author.yaml to person.yaml
- rename AuthorPreview to PersonPreview
- add contributor and editor as possible metadata fields to the front matter, using persons from person.yaml
- do not display editors and contributors yet, we'll have to redesign how we display metadata on individual resources —  the current minimal design is too limiting and we'll have more fields to display then we currently do.

**Comment by stefanprobst** [comment]
ok :+1:

also, may i suggest that we use full names for the author/editor/contributor slugs -- those need to be unique and i think it's better to do `klaus-illmayer` than `klaus` right from the start, rather than having to change this midway, or invent an elaborate naming scheme like `klaus-i2` -- let me know what you think!

**Comment by DeborahThorpe** [comment]
Yes, agree. Full names would be much better, because we only have a few entries and already have multiples of certain more common names!

**Comment by DeborahThorpe** [comment]
Shall I make those changes to the existing ones and their corresponding resources?

**Comment by stefanprobst** [comment]
@DeborahThorpe i went ahead and changed the slugs in `person.yaml` and in the frontmatter metadata fields

also: it's now possible to add `editors` and `contributors`

**Comment by ttasovac** [comment]
Yes, pretty please! 
--
Belgrade Center for Digital Humanities
http://humanistika.org

**Comment by ttasovac** [comment]
thanks @stefanprobst! not to mention that your "fake" masonry layout looks great. In terms of the length differences between abstracts, we'll see if anything breaks the layout, but so far, it looks good.

@DeborahThorpe could you now go back and enter editors and contributors in those articles where they were needed. After you do that, you can close this issue.

**Comment by ttasovac** [comment]
actually, let's not close this yet.

@stefanprobst editorial and master and now fully merged, but I'm getting an error which doesn't exist on netlify:

`http://localhost:8000/author/klaus-thoden`

or any of the newly renamed authors will give me 

<img width="1088" alt="Скриншот 2019-08-14 07 50 47" src="https://user-images.githubusercontent.com/5304839/62997350-3f563000-be68-11e9-9854-1e82f475fbc8.png">

**Comment by stefanprobst** [comment]
I'm not seeing this locally. This is with a restarted development server? If yes, try cleaning the cache with `yarn clean` before running `yarn develop`.

**Comment by ttasovac** [comment]
Yesssss, it was a cache issue. Thanks @stefanprobst.

Back to @DeborahThorpe, you can close this issue once you've entered the missing editors etc. to the existing articles.

**Comment by DeborahThorpe** [comment]
Ok, I've added them - but before I close - should we change the path for images to 'person'/'people' now rather than authors?

**Comment by ttasovac** [comment]
the folder where the images are held is still called authors, so the paths are correct. we will also have to change the folder name, but let me do that later...

for the time being, keep using the old paths... once i make the change, you will see, when you fetch the latest version, that all the paths in person.yaml have changes, so you will know that you should use them from then on

amen! 

:)
