### ISSUE TITLE
video cards

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#16]
A couple of things:

- videos on the home page (Why training and education) don't work. We get a blank lightbox, but no video plays.
- Training Videos is currently a component with hardcoded videos. It would be nice if we could transform this into a component called Featured Videos that would be filled with videos from /contents/data/featuredVideos.yaml (together with Title and LeadIn for this section)
- Finally, we'd need a proper video card component so that we can use video cards in resources as well. (this is because we want, for instance, to use our own screenshots for the videos etc.)

We still want to keep the YouTube component, of course, for embedding videos directly so to speak. But a video card component should work like the training videos on the front page: you click, and the video opens and autoplays in full-screen lightbox.

@stefanprobst, because this is important for @DeborahThorpe to finish porting our content, could you please work on this before everything else.

many thanks in advance!

**Comment by stefanprobst** [comment]
>     * videos on the home page (Why training and education) don't work. We get a blank lightbox, but no video plays.

that's odd. this used to work at some point, i'll take a look

>     * Finally, we'd need a proper video card component

:+1:

>     * a component called Featured Videos that would be filled with videos from /contents/data/featuredVideos.yaml

suggestion: instead of having another yaml config file, we could do this similar to `faq.mdx`

**Comment by ttasovac** [comment]
> suggestion: instead of having another yaml config file, we could do this similar to faq.mdx

yes, absolutely!

**Comment by DeborahThorpe** [comment]
I've finished porting the non-video content today, so am ready to move onto the videos whenever we're ready.

**Comment by ttasovac** [comment]
The syntax for video cards will be:

```html
<VideoCard
  id="OqYJNUmhJzw"
  title="Laurent Romary"
  subtitle="Former DARIAH Director"
  image="assets/laurent-romary.jpg"
/>
```

where:

- **id** is the YouTube video id,
- **title** and **subtitle** are, oh well... 
- **image** points to the screenshot which we should, by convention, put in a folder called assets within the folder of the given resource.

I don't think @stefanprobst has finished working on the video cards because I can't compile this in a resource, but the syntax _is_ what it is, so it's safe that you start adding all those video resources as is.

**Comment by stefanprobst** [comment]
yes you can start adding it like this -- every resource should have an `images` folder where you can put the screenshots.

the thing that i need to figure out is: what is the best way to process those images with Gatsby's optimization pipeline, without the content creators having to write queries themselves. there are different approaches and i need to first try those. it will probably mean having an `images` property on `<VideoCard images={props.images} />` that injects the optimized images and you just need to copypaste that when using the VideoCard. But we'll see.

It's holiday today here, so i'll probably only finish this tomorrow, but please go ahead adding the `VideoCards` and i'll fix things later.

**Comment by stefanprobst** [comment]
ok, earlier than promised, this is how the `VideoCard` component works:

* put the images in a `images` subfolder of your resource. e.g.:
```
/2019-my-resource/
  - resource.mdx
  - images/screenshot.png
```
* use it in the mdx file like this:
```jsx
<VideoCard
  title="Title"
  subtitle="Subtitle"
  id="some-youtube-video-id"
  image="images/screenshot.png"
  images={props.images}
/>
```

We *might* be able to get rid of the `images` prop but i can't promise that yet, might need upstream changes.

**Comment by stefanprobst** [comment]
also a heads up: i changed 2 dependencies in the master branch, so you'll need to run `yarn` to update yours.

**Comment by DeborahThorpe** [comment]
Ok, I'm going to start adding those video resources now. Let me know if you see any problems!

**Comment by ttasovac** [comment]
@stefanprobst thanks a lot! 

yes, it would be great if you could find a way to deal with the prop automatically. 

also, could you also make the youtube video autoplay _when it's started from the video card_? I.e. the YouTube component itself should _not_ have autoplay on, but when a user clicks on a video card and the youtube video opens in a lightbox, it would be better if the video would start playing automatically, because the user had already clicked once.

**Comment by stefanprobst** [comment]
> could you also make the youtube video autoplay _when it's started from the video card_

done

**Comment by ttasovac** [comment]
yesssss. pefect! 
--
Belgrade Center for Digital Humanities
http://humanistika.org

**Comment by stefanprobst** [comment]
> yes, it would be great if you could find a way to deal with the prop automatically.

done, no need to add the extra `images` prop anymore

**Comment by DeborahThorpe** [comment]
Thanks for letting us know @stefanprobst , so for ones that I am uploading today, I will omit 'images={props.images}', if I understand correctly...?
