### ISSUE TITLE
Please don't push stuff to master that does not compile

### ISSUE THREAD

**Issue by stefanprobst** [stefanprobst/dariah-campus-mdx#17]
It would be *really* helpful if you could check running the development server if things compile before pushing to master. We have had breakage on both merges from the editorial branch (missing closing tag, non-escaped quotes).
Thanks!

**Comment by stefanprobst** [comment]
If your text editor supports it, installing a syntax-highlighter for MDX can be really helpful to spot these errors early. I am using the one for VS Code.

**Comment by ttasovac** [comment]
Sure —  sorry about that. But I'm not sure what I'm doing wrong. I have the development server running all the time.

So just to clarify, when I merge editorial into master locally, i should run `yarn develop` on the master and make sure there are no errors in Terminal. Am I missing anything else?

**Comment by stefanprobst** [comment]
yes please.

afaik Gatsby will only source data once at the beginning of a `develop` run, and then watch those sources for changes for hot module reloading.
so when adding *new* files, i think for those to be picked up you'd need to restart the development server. i guess this is why you didn't see the compile errors?

**Comment by ttasovac** [comment]
Got it! Will always check from now on. But, of course, do tell me if it happens again for some reason...
