### ISSUE TITLE
blank line after last metadata field needed

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#21]
If the metadata section ends like this:

```
type: video
---
```

we'll get the yaml exception about a multiline key etc... 

For the resource to compile correctly, the metadata section needs to end like this:

```
type: video

---
```

i.e. there has to be an empty line before the end-of-the-metadata delimiters.

@stefanprobst: is this a bug or a feature? if it's a bug, it would be really nice to get rid of it.

@DeborahThorpe: for the time being and depending on what Stefan tells us, please make sure we have a blank line separating the last metadata entry from the "---".  Hopefully this is temporary. If it isn't we'll have to make sure this gets noted in the markdown template in the authors' guidelines.

**Comment by stefanprobst** [comment]
hmm, I'm not getting this. i have actually even added some auto-formatting to enforce a more uniform layout (with a git commit hook), which would remove the empty line anyway.

we can quickly debug this in our call later today
