### ISSUE TITLE
thinner fonts

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#3]
I prefer the "thinner" fonts of the original design, both in the navbar and the content, so let's try to mimic those please.

Original:

![Снимок экрана 2019-08-06 в 14 11 09](https://user-images.githubusercontent.com/5304839/62538945-4cfe2b00-b854-11e9-8675-6152bc1d590a.png)

vs. 

Current:

![Снимок экрана 2019-08-06 в 14 11 38](https://user-images.githubusercontent.com/5304839/62538973-5be4dd80-b854-11e9-9e72-e1a51df2955d.png)

**Comment by stefanprobst** [comment]
hopefully fixed (though personally i prefer the heavier version with). if there's more to adjust, please reopen
