### ISSUE TITLE
incorrect links from post metadata to tag and author page

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#4]
Links from tags in individual posts (such as DH in https://dariah-campus.netlify.com/resource/introduction-to-digital-humanities) currently point to https://dariah-campus.netlify.com/tags/dh, but this is wrong, they should point to: https://dariah-campus.netlify.com/tag/dh

**Comment by ttasovac** [comment]
The same problem occurs with links to authors. Currently, links point to /authors/AUTHORNAME but that leads to a page no found. The correct link is /author/AUTHORNAME

**Comment by stefanprobst** [comment]
fixed
