### ISSUE TITLE
we need better image quality in author avatars

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#6]
I'm not sure the screenshots will help here because the screenshots will get compressed themselves, but if you compare https://dariah-eric.github.io/dariah-campus/ and https://dariah-campus.netlify.com/ you will see that author images are too blurry in the new version.

I understand Gatsby helps us compress and produce different versions of the same image, but here I think we compressed too much. 

Original:

![Снимок экрана 2019-08-06 в 14 52 50](https://user-images.githubusercontent.com/5304839/62541371-f5fb5480-b859-11e9-97c6-a9280263b95d.png)

Current:

![Снимок экрана 2019-08-06 в 14 53 10](https://user-images.githubusercontent.com/5304839/62541410-04497080-b85a-11e9-9c3d-00b4567518e9.png)

again, please check the above links to see the difference more clearly

**Comment by stefanprobst** [comment]
increased `quality` setting to 100
