### ISSUE TITLE
use abstract as a teaser in posts

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#7]
At the moment, the text which is displayed as a teaser for posts on /resources or /tag/dh is cut off after a certain number of characters. This is not the desired behavior.

We should be displaying the full abstract from the post metadata as a teaser.

**Comment by stefanprobst** [comment]
just to clarify: you also want to keep the masonry layout?

**Comment by ttasovac** [comment]
Yes, pretty please 😃

**Comment by ttasovac** [comment]
oh, and one more thing regarding the masonry layout. it should be responsive, of course, and it should use three columns in a wide view, two columns for tablets and one column for mobile, like here: https://dariah-eric.github.io/dariah-campus/resources/ 

fun times! 🎈 🎉

**Comment by stefanprobst** [comment]
:+1: i think i'll write my own because the masonry implementations out there either do too much (for what we need), or have a too simple layout algorithm. hopefully over the weekend
