### ISSUE TITLE
wider container for course registry

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#8]
This is another small cosmetic thing. The embedded Course Registry page is very wide, so it needs a wider container than the regular pages on DARIAH-CAMPUS. 

Compare https://dariah-eric.github.io/dariah-campus/course-registry and http://localhost:8000/course-registry —  we want to show the whole map and all the columns (information and curriculum).

**Comment by stefanprobst** [comment]
done
