### ISSUE TITLE
collaborators and editoral branch

### ISSUE THREAD

**Issue by ttasovac** [stefanprobst/dariah-campus-mdx#9]
Hi Stefan.

First of all, many thanks for efficiently taking care of the issues I posted the other day.

Could you please make myself and @deborahthorpe collaborators in this repo? I would like to create an editorial branch so that we can start moving the content from the old site to the mdx. 

We'll use the editorial branch only for adding content, so merging should not be too difficult. I will keep the editorial branch up to date with your changes, and then once in a while make a pull request so that you merge it into the master branch. So you can ignore what Debs and I do there until you get a pull request.

Let me know if this is ok with you, or if you'd prefer a different workflow.

All best,
Toma

**Comment by stefanprobst** [comment]
Sure no problemo!

**Comment by stefanprobst** [comment]
one thing we might want to do is move the content folders (i.e. `posts`, `data` and `events`) out of `/src` to keep things better separated

**Comment by ttasovac** [comment]
oh, that would be great! please go ahead and turn those into top-level folders. actually, i think it would be even more elegant if we had `data` as a top-level folder, and then another top-level folder called `content`, which would contain `resources` and `events`. 

i prefer `resources` to `posts` because we use `/resources` in the url and not `/posts.` 

by the way, i don't know if i made this clear earlier on, but events (even though they are separate on the file system, and even though they use a different layout) should also show up in the `/resources` overview to the end user. as far as the user is concerned, events are a subcategory of resources...

we can discuss this further today if it's not clear.

**Comment by stefanprobst** [comment]
oh yeah let's quickly talk about this on today's call -- i was *not* aware of that and actually wanted to ask if we need a `/events` overview page.

**Comment by ttasovac** [comment]
actually, i think i may have spoken too soon. i just realized that i did plan to have a separate events page in the old design, i just never finished it, but i see i did create a placeholder.

the important thing for me was that events and resources would be searchable in the same way... i.e. when you search for "open" in the old design, you get the "open data citation" which is an event as well as "open education and moocs" which is a resource.

the subcategory of resources is not actually events but collections... (which we should rename to pathfinders... pathfinders are guides to the best resources out there on a specific topic. you correctly created a "source" for them, i think that's the best way of dealing with them...

so... yes, let's revisit this today so that I don't keep adding confusion to the issue with my not well-thought-through posts... :)

**Comment by DeborahThorpe** [comment]
Hi, I'd love to drop in today to listen in on the ongoing developments. What time are you talking?
